---

- name: Gather necessary facts and/or variables
  ansible.builtin.setup:
    filter:
      - ansible_os_family
      - ansible_env

- name: "[Debian] Ensure python3-debian is present" # Needed to detect which package manager to use on Debian, as well as for deb822_repository module
  ansible.builtin.apt:
    name: python3-debian
    state: present
  when: ansible_os_family in ['Debian']

- name: Gather packages facts
  ansible.builtin.package_facts:
    manager: auto
