---

- name: "[IMPORT] Import tasks \"gather_facts_subset.yml\""
  ansible.builtin.import_tasks: gather_facts_subset.yml
  tags:
    - apt
    - dnf
    - flatpak
    - install
    - update
    - apt+install
    - dnf+install
    - apt+update
    - dnf+update
    - flatpak+install
    - flatpak+update

- name: Group system packages related tasks
  block:
    - name: "[INCLUDE] Include tasks \"setup_custom_repositories_<linux_distribution>.yml\""
      ansible.builtin.include_tasks:
        file: "setup_custom_repositories_{{ ansible_os_family|d('Debian')|lower }}.yml"
        apply: # Even though included_tasks effectively inherit tags from blocks, they shouldn't (see https://github.com/ansible/ansible/issues/84127). So I'll keep the extra apply here just in case
          tags:
            - apt
            - dnf
            - install
            - apt+install
            - dnf+install
      tags:
        - install
        - apt+install
        - dnf+install

    - name: "[INCLUDE] Include tasks \"setup_base_packages_<linux_distribution>.yml\""
      ansible.builtin.include_tasks:
        file: "setup_base_packages_{{ ansible_os_family|d('Debian')|lower }}.yml"
        apply:
          tags:
            - apt
            - dnf
            - install
            - apt+install
            - dnf+install
      tags:
        - install
        - apt+install
        - dnf+install

    - name: "[INCLUDE] Include tasks \"update_packages_<linux_distribution>.yml\""
      ansible.builtin.include_tasks:
        file: "update_packages_{{ ansible_os_family|d('Debian')|lower }}.yml"
        apply:
          tags:
            - apt
            - dnf
            - update
            - apt+update
            - dnf+update
      tags:
        - update
        - apt+update
        - dnf+update
        - never

  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - apt
    - dnf

- name: Group flatpak packages related tasks
  block:
    - name: "[IMPORT] Import tasks \"setup_custom_repositories_flatpak.yml\""
      ansible.builtin.import_tasks: setup_custom_repositories_flatpak.yml
      tags:
        - install
        - flatpak+install

    - name: "[IMPORT] Include tasks \"setup_base_packages_flatpak.yml\""
      ansible.builtin.import_tasks: setup_base_packages_flatpak.yml
      tags:
        - install
        - flatpak+install

    - name: "[IMPORT] Include tasks \"update_packages_flatpak.yml\""
      ansible.builtin.import_tasks: update_packages_flatpak.yml
      tags:
        - update
        - flatpak+update
        - never

  when: "'flatpak' in ansible_facts.packages"
  tags:
    - flatpak

- name: Group standalone binaries related tasks
  block:
    - name: "[IMPORT] Import tasks \"gather_facts_subset.yml\"" # Run these tasks there (possibly again) because this task group don't run as root
      ansible.builtin.import_tasks: gather_facts_subset.yml

    - name: "[IMPORT] Import tasks \"setup_update_packages_binaries.yml\""
      ansible.builtin.import_tasks: setup_update_packages_binaries.yml

  vars:
    ansible_become: false
  tags:
    - bin
    - install
    - bin+install
    - update
    - bin+update
