---

- name: "[IMPORT] Import tasks \"gather_facts_subset.yml\""
  ansible.builtin.import_tasks: gather_facts_subset.yml

- name: "[INCLUDE] Import tasks \"setup_custom_repositories_<linux_distribution>.yml\""
  ansible.builtin.include_tasks: "setup_custom_repositories_{{ ansible_os_family|d('Debian')|lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: "[INCLUDE] Include tasks \"setup_base_packages_<linux_distribution>.yml\""
  ansible.builtin.include_tasks: "setup_base_packages_{{ ansible_os_family|d('Debian')|lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat']

- name: "[INCLUDE] Include tasks \"update_packages_<linux_distribution>.yml\""
  ansible.builtin.include_tasks: "update_packages_{{ ansible_os_family|d('Debian')|lower }}.yml"
  when: ansible_os_family in ['Debian', 'RedHat']
  tags:
    - never

- name: "[IMPORT] Import tasks \"setup_custom_repositories_flatpak.yml\""
  ansible.builtin.import_tasks: setup_custom_repositories_flatpak.yml

- name: "[IMPORT] Include tasks \"setup_base_packages_flatpak.yml\""
  ansible.builtin.import_tasks: setup_base_packages_flatpak.yml

- name: "[IMPORT] Include tasks \"update_packages_flatpak.yml\""
  ansible.builtin.import_tasks: update_packages_flatpak.yml
  tags:
    - never
