---

- name: "[Debian] Ensure python3-debian is present"
  ansible.builtin.apt:
    name: python3-debian
    state: present

- name: "[Debian] Add apt custom repository"
  ansible.builtin.deb822_repository:
    name: "{{ item.repoName }}"
    types: "{{ item.repoTypes|d(['deb']) }}"
    uris: "{{ item.repoBaseUrl }}"
    suites: "{{ item.repoDistributionReleases|d(['/']) }}"
    components: "{{ item.repoComponents|d(omit) }}"
    architectures: "{{ item.repoArchitecture|d(['amd64']) }}"
    signed_by: "{{ item.repoSigningKey|d(omit) }}"
    trusted: "{{ item.repoIsTrusted|bool|d(omit) }}"
    mode: 0644
    state: present
  loop: "{{ ansible_bin_apt_custom_repositories_common|d([]) + ansible_bin_apt_custom_repositories|d([]) }}"
