---

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item.pkgId }}"
    method: "{{ item.pkgInstallMethod|d('user') }}"
    state: present
  loop: "{{ ansible_bin_flatpak_packages_common|d([]) + ansible_bin_flatpak_packages|d([]) }}"
