---

- name: Add flatpak custom remotes
  community.general.flatpak_remote:
    name: "{{ item.repoName }}"
    flatpakrepo_url: "{{ item.repoUrl }}"
    method: "{{ item.repoInstallMethod|d('user') }}"
    state: present
  loop: "{{ ansible_bin_flatpak_custom_repositories_common|d([]) + ansible_bin_flatpak_custom_repositories|d([]) }}"
