---

- name: "[INFO] [Debian] Print holded packages"
  ansible.builtin.debug:
    msg:
      - "Holded packages:"
      - "{{ ansible_bin_packages_versionlock_common|d([]) + ansible_bin_packages_versionlock|d([]) }}"
  when: (ansible_bin_packages_versionlock_common|d([]) + ansible_bin_packages_versionlock|d([])) | length>0

- name: "[Debian] Hold packages"
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ ansible_bin_packages_versionlock_common|d([]) + ansible_bin_packages_versionlock|d([]) }}"
  changed_when: false

- name: "[Debian] Update packages"
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    name: "*"
    state: latest
  register: _ansible_bin_packages_update_output

- name: "[Debian] Parse updated packages (check mode)"
  ansible.builtin.set_fact:
    _updated_packages: >-
      {{
        _ansible_bin_packages_update_output.stdout_lines|d()
        | select('match', '^Inst ')
        | map('regex_replace', '^Inst (\S+) \[([^\]]+)\] \((\S+).*', '\1: \2 -> \3')
        | list
      }}
  when: ansible_check_mode

- name: "[Debian] Parse updated packages (normal mode)"
  ansible.builtin.set_fact:
    _updated_packages: >-
      {{
        _ansible_bin_packages_update_output.stdout_lines|d()
        | select('match', '^Unpacking ')
        | map('regex_replace', '^Unpacking (\S+) \(([^)]+)\) over \(([^)]+)\).*', '\1: \3 -> \2')
        | list
      }}
  when: not ansible_check_mode

- name: "[INFO] [Debian] Print updated packages"
  ansible.builtin.debug:
    msg: "{{ _updated_packages }}"
  when:
    - _ansible_bin_packages_update_output.changed
    - _updated_packages | length > 0

- name: "[Debian] Cleanup"
  ansible.builtin.apt:
    autoremove: true

- name: "[Debian] Unhold packages"
  ansible.builtin.dpkg_selections:
    name: "{{ item }}"
    selection: install
  loop: "{{ ansible_bin_packages_versionlock_common|d([]) + ansible_bin_packages_versionlock|d([]) }}"
  changed_when: false

- name: "[Debian] Check if a reboot is needed"
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: _ansible_bin_rebootcheck_output
  changed_when: _ansible_bin_rebootcheck_output.stat.exists|d()|bool
  notify:
    - System-reboot

- name: Execute handlers immediately
  ansible.builtin.meta: flush_handlers
