---

- name: Verify
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Gather necessary facts and/or variables
      ansible.builtin.setup:
        filter:
          - ansible_env
          - ansible_os_family

  tasks:
    - name: Verify apt custom repository files exists
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d/
        patterns: "{{ item.repoName }}.*"
      register: _tests_apt_repo_files
      loop: "{{ ansible_bin_apt_custom_repositories_common | d([]) + ansible_bin_apt_custom_repositories | d([]) }}"
      when: ansible_os_family == 'Debian'

    - name: Assert apt custom repositories are present
      ansible.builtin.assert:
        that: _tests_apt_repo_files.results[index].files | length > 0
        fail_msg: "Repository file for '{{ item.repoName }}' is missing"
        success_msg: "Repository file for '{{ item.repoName }}' is present"
      loop: "{{ ansible_bin_apt_custom_repositories_common | d([]) + ansible_bin_apt_custom_repositories | d([]) }}"
      loop_control:
        index_var: index
      when: ansible_os_family == 'Debian'

    - name: Verify packages are installed
      ansible.builtin.package_facts:
        manager: auto

    - name: Assert system packages are installed
      ansible.builtin.assert:
        that: item in ansible_facts.packages
        fail_msg: "Package '{{ item }}' is not installed"
        success_msg: "Package '{{ item }}' is installed"
        quiet: true
      loop: >-
        {{ (ansible_bin_apt_packages_common | d([]) + ansible_bin_apt_packages | d([]))
        if ansible_os_family == 'Debian'
        else (ansible_bin_dnf_packages_common | d([]) + ansible_bin_dnf_packages | d([]))
        if ansible_os_family == 'RedHat'
        }}

    - name: Get installed flatpak packages
      ansible.builtin.command:
        cmd: flatpak list --app --columns=application
      register: _tests_flatpak_packages
      changed_when: false
      check_mode: false

    - name: Assert flatpak packages are installed
      ansible.builtin.assert:
        that: item.pkgId in _tests_flatpak_packages.stdout_lines
        fail_msg: "Flatpak package '{{ item.pkgId }}' is not installed"
        success_msg: "Flatpak package '{{ item.pkgId }}' is installed"
        quiet: true
      loop: "{{ ansible_bin_flatpak_packages_common | d([]) + ansible_bin_flatpak_packages | d([]) }}"

    - name: Print results with cowsay
      ansible.builtin.command: cowsay "All tests passed on {{ inventory_hostname }} !"
      changed_when: false
      environment:
        PATH: "/usr/games:{{ ansible_env.PATH }}"
      register: _tests_result_output

    - debug:
        msg: "{{ _tests_result_output.stdout_lines }}"
